### PR TITLE
Unify & refactor transport implementations for tcp-based/udp-based protocols

### PR DESCRIPTION
**Pull request by laugengebaeck**
This is a try on how to implement (and would close) #55. If we're already working on this, we should probably also tidy up the whole transport implementation a bit (are there methods or parameters noone needs etc.)

Important changes:
- removes `RASTA_TLS_MODE` config option, this now handled by linking against the librasta of your choice
- changes the signatures of many internal (transport) methods (e.g. `transport_close` is replaced by `transport_close_channel`, with `transport_close_socket` being added additionally)

### CODE REVIEW

**Comment by laugengebaeck** [comment]
Idea: We should have a `transport_close_socket` function, to make use of `udp_close` (currently unused, doesn't make sense to close a channel in the UDP case -> should be socket) and to prevent the "I closed the channel fd, but not the socket fd" sort of problems.

**Comment by laugengebaeck** [comment]
Also: Can we please get rid of the "doing different stuff based on `tls_mode`" for TLS and DTLS? TLS without TLS enabled is just TCP, and DTLS without DTLS enabled is just UDP. Also, some methods choose not to respect `tls_mode`, so even this is inconsistent.

**Comment by laugengebaeck** [comment]
TODO:

- check if both `transport_close_socket` implementations make sense
- add tests for `transport_close_socket`?
- fix that weird TLS test bug that only happens in CI

**Review by rs22 — APPROVED** [review]
Thanks! 

Regarding the issues you had with non-initialized structs, maybe we can enable valgrind during the test execution? I think there are some remains of an integration in the CMake files. Let's put this on the backlog.

**Pull request merged**
